"""Regenerate the static assets the site in docs/ uses.

    python scripts/build-site-assets.py [screenshot-dir]

- Manrope TTF -> docs/assets/fonts/*.woff2 (needs fonttools + brotli)
- apps/device-center/qml/DotGlyphs.js -> docs/assets/dotglyphs.js, so the
  site's dot-matrix type is the app's, glyph for glyph
- the WH-1000XM5 render -> docs/assets/halftone.js, a precomputed dot grid
  (no image decoding at runtime, so the page also works from file://)
- optional: app captures from SONY_UI_SCREENSHOTS runs ->
  docs/assets/shots/<name>-<theme>.webp. The directory must hold
  light/ and dark/ subfolders with pageN.png and hub.png.
"""
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "assets"


def fonts() -> None:
    from fontTools.ttLib import TTFont
    (OUT / "fonts").mkdir(parents=True, exist_ok=True)
    for weight in ("Regular", "Medium", "SemiBold", "Bold"):
        font = TTFont(ROOT / "assets" / "fonts" / "Manrope" / f"Manrope-{weight}.ttf")
        font.flavor = "woff2"
        font.save(OUT / "fonts" / f"manrope-{weight.lower()}.woff2")


def glyphs() -> None:
    src = (ROOT / "apps" / "device-center" / "qml" / "DotGlyphs.js").read_text(encoding="utf-8")
    body = src.replace(".pragma library", "").strip()
    out = ("// Generated by scripts/build-site-assets.py from the app's DotGlyphs.js.\n"
           "(function () {\n" + body + "\nwindow.DotGlyphs = { table: table, normalize: normalize };\n})();\n")
    (OUT / "dotglyphs.js").write_text(out, encoding="utf-8", newline="\n")


def halftone(columns: int = 84) -> None:
    img = Image.open(ROOT / "Client" / "resources" / "devices" / "wh-1000xm5.png").convert("RGBA")
    img = img.crop(img.getbbox())
    cell = img.width / columns
    rows = int(img.height / cell)
    small = img.resize((columns, rows), Image.LANCZOS)
    def luma(p):
        return (0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2]) / 255
    # A black product is dark all over: stretch its own tonal range so the
    # highlights read as smaller dots rather than drowning in ink.
    pixels = [small.getpixel((x, y)) for y in range(rows) for x in range(columns)]
    body = sorted(luma(p) for p in pixels if p[3] > 128)
    lo, hi = body[len(body) // 20], body[len(body) * 19 // 20]
    lines = []
    for y in range(rows):
        line = []
        for x in range(columns):
            px = small.getpixel((x, y))
            lum = min(1.0, max(0.0, (luma(px) - lo) / max(0.01, hi - lo)))
            ink = (px[3] / 255) * (0.3 + 0.7 * (1 - lum) ** 0.8)
            line.append(str(min(9, round(ink * 9))))
        lines.append("".join(line))
    out = ("// Generated by scripts/build-site-assets.py: the WH-1000XM5 render as a\n"
           "// dot grid, one digit (0-9) of ink per cell.\n"
           f"window.HALFTONE = {{ columns: {columns}, rows: {rows}, cells: \"{''.join(lines)}\" }};\n")
    (OUT / "halftone.js").write_text(out, encoding="utf-8", newline="\n")


def trim_bottom(img: Image.Image) -> Image.Image:
    """Drop the uniform strip a capture of a small window can carry below it."""
    last = [img.getpixel((x, img.height - 1)) for x in range(0, img.width, 7)]
    bottom = img.height
    while bottom > 1 and [img.getpixel((x, bottom - 1)) for x in range(0, img.width, 7)] == last:
        bottom -= 1
    return img.crop((0, 0, img.width, bottom)) if bottom < img.height - 2 else img


def shots(src: Path) -> None:
    names = {"page0.png": "overview", "page1.png": "noise", "page2.png": "equalizer",
             "page5.png": "battery", "hub.png": "hub"}
    (OUT / "shots").mkdir(parents=True, exist_ok=True)
    for theme in ("light", "dark"):
        for file, name in names.items():
            path = src / theme / file
            if not path.exists():
                continue
            img = Image.open(path).convert("RGB")
            if name == "hub":
                img = trim_bottom(img)
            if img.width > 1400:
                img = img.resize((1400, round(img.height * 1400 / img.width)), Image.LANCZOS)
            img.save(OUT / "shots" / f"{name}-{theme}.webp", "WEBP", quality=88, method=6)


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    fonts()
    glyphs()
    halftone()
    if len(sys.argv) > 1:
        shots(Path(sys.argv[1]))
