"""Generate the donation QR code for the app, the site and the README.

The address is plain text in the code (no payment URI): every wallet reads a
bare address, few agree on the URI forms. The code is drawn in the app's own
dot style: round data dots, rounded finder squares.

Usage (needs `pip install segno`):
    python scripts/make-donation-qr.py

Writes:
    apps/device-center/qml/Donation.js   address, network, module matrix
    docs/assets/donate-qr.svg            the same code for the site / README
"""
from pathlib import Path

import segno

ROOT = Path(__file__).resolve().parent.parent
ADDRESS = "0xB38514c1818F3bE86656b2E75D4B95bA02D14284"
COIN = "USDT"
NETWORK = "Ethereum (ERC-20)"


def matrix() -> list[str]:
    code = segno.make(ADDRESS, error="m", micro=False, boost_error=True)
    return ["".join("#" if bit else "." for bit in row) for row in code.matrix]


def is_finder(rows: list[str], r: int, c: int) -> bool:
    n = len(rows)
    return any(r0 <= r < r0 + 7 and c0 <= c < c0 + 7 for r0, c0 in ((0, 0), (0, n - 7), (n - 7, 0)))


def svg(rows: list[str], module: int = 10, quiet: int = 4) -> str:
    n = len(rows)
    size = (n + 2 * quiet) * module
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}">',
             f'<rect width="{size}" height="{size}" rx="{module * 2}" fill="#fff"/>',
             '<g fill="#111">']
    for r0, c0 in ((0, 0), (0, n - 7), (n - 7, 0)):
        x, y = (c0 + quiet) * module, (r0 + quiet) * module
        m = module
        # Ring (7x7 minus 5x5) as an even-odd path, then the 3x3 eye.
        parts.append(
            f'<path fill-rule="evenodd" d="M{x + 2 * m} {y}h{3 * m}a{2 * m} {2 * m} 0 0 1 {2 * m} {2 * m}v{3 * m}'
            f'a{2 * m} {2 * m} 0 0 1 {-2 * m} {2 * m}h{-3 * m}a{2 * m} {2 * m} 0 0 1 {-2 * m} {-2 * m}v{-3 * m}'
            f'a{2 * m} {2 * m} 0 0 1 {2 * m} {-2 * m}z'
            f'M{x + 2 * m} {y + m}h{3 * m}a{m} {m} 0 0 1 {m} {m}v{3 * m}a{m} {m} 0 0 1 {-m} {m}h{-3 * m}'
            f'a{m} {m} 0 0 1 {-m} {-m}v{-3 * m}a{m} {m} 0 0 1 {m} {-m}z"/>')
        parts.append(f'<rect x="{x + 2 * m}" y="{y + 2 * m}" width="{3 * m}" height="{3 * m}" rx="{m}"/>')
    radius = module * 0.46
    for r, row in enumerate(rows):
        for c, bit in enumerate(row):
            if bit == "#" and not is_finder(rows, r, c):
                cx, cy = (c + quiet + 0.5) * module, (r + quiet + 0.5) * module
                parts.append(f'<circle cx="{cx:g}" cy="{cy:g}" r="{radius:g}"/>')
    parts.append("</g></svg>\n")
    return "\n".join(parts)


def main() -> None:
    rows = matrix()
    js = ["// Generated by scripts/make-donation-qr.py; edit the script, not this file.",
          ".pragma library",
          "",
          f'var address = "{ADDRESS}"',
          f'var coin = "{COIN}"',
          f'var network = "{NETWORK}"',
          "// QR modules, top row first; '#' is dark. No quiet zone.",
          "var qr = ["]
    js += [f'    "{row}",' for row in rows]
    js[-1] = js[-1].rstrip(",")
    js.append("]")
    (ROOT / "apps/device-center/qml/Donation.js").write_text("\n".join(js) + "\n", encoding="utf-8", newline="\n")
    (ROOT / "docs/assets/donate-qr.svg").write_text(svg(rows), encoding="utf-8", newline="\n")
    print(f"{len(rows)}x{len(rows)} modules")


if __name__ == "__main__":
    main()
